# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# Ex: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

def sum_of_even_fib_seq(max):
    all_fibs = [1, 2]
    even_fibs = []
    while all_fibs[-1] + all_fibs[-2] <= max:
        if all_fibs[-1] % 2 == 0:
            even_fibs.append(all_fibs[-1])
        all_fibs.append(all_fibs[-1] + all_fibs[-2])

    even_fibs.append(all_fibs[-1])

    print(even_fibs)
    print(all_fibs)
    print(sum(even_fibs))

sum_of_even_fib_seq(4000000)

